apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata: { name: datahub }
spec: { refreshInterval: 1h, secretStoreRef: { name: edai2-vault, kind: ClusterSecretStore }, target: { name: datahub }, data: [{ secretKey: system-update-password, remoteRef: { key: edai2/platform/datahub, property: system-update-password } }] }
