apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata: { name: jenkins-controller }
spec: { refreshInterval: 1h, secretStoreRef: { name: edai2-vault, kind: ClusterSecretStore }, target: { name: jenkins-controller }, data: [{ secretKey: admin-user, remoteRef: { key: edai2/jenkins/controller, property: admin-user } }, { secretKey: admin-password, remoteRef: { key: edai2/jenkins/controller, property: admin-password } }] }
