{{- if .Values.autoscaling.enabled }}
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ .Values.workload.name }}
  namespace: {{ .Values.namespace }}
spec:
  scaleTargetRef:
    name: {{ .Values.workload.name }}
  minReplicaCount: {{ .Values.autoscaling.minReplicaCount }}
  maxReplicaCount: {{ .Values.autoscaling.maxReplicaCount }}
{{- end }}
