apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: edai2-private-gateway
  namespace: edai2
spec:
  gatewayClassName: agentgateway
  listeners:
    - name: http
      protocol: HTTP
      port: 8080
