name: vina_bim_shop
version: "1.0.0"
config-version: 2
profile: vina_bim_shop

model-paths: ["models"]
macro-paths: ["macros"]
test-paths: ["tests"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

on-run-start:
  - "{{ reset_gold_schema() }}"

models:
  vina_bim_shop:
    bronze:
      +materialized: view
      +schema: bronze
    silver:
      +materialized: view
      +schema: silver
    gold:
      +materialized: table
      +schema: gold

vars:
  raw_root: data/raw
