version: 2

models:
  - name: feat_customer_90d
    config:
      contract:
        enforced: true
    constraints:
    - type: primary_key
      columns:
      - customer_id
      - event_timestamp
    columns:
    - name: customer_id
      data_type: varchar
      constraints:
      - type: not_null
      - type: foreign_key
        to: ref('dim_customer')
        to_columns:
        - customer_id
      tests:
      - not_null
    - name: event_timestamp
      data_type: timestamp
      constraints:
      - type: not_null
      tests:
      - not_null
    - name: f_customer_total_orders_90d
      data_type: bigint
    - name: f_customer_paid_revenue_90d
      data_type: double
    - name: f_customer_avg_order_value_90d
      data_type: double
    - name: f_customer_distinct_categories_90d
      data_type: bigint
    - name: created
      data_type: timestamp
  - name: feat_stream_60m
    config:
      contract:
        enforced: true
    constraints:
    - type: primary_key
      columns:
      - customer_id
      - event_timestamp
    columns:
    - name: customer_id
      data_type: varchar
      constraints:
      - type: not_null
      - type: foreign_key
        to: ref('dim_customer')
        to_columns:
        - customer_id
      tests:
      - not_null
    - name: event_timestamp
      data_type: timestamp
      constraints:
      - type: not_null
      tests:
      - not_null
    - name: f_stream_views_60m
      data_type: hugeint
    - name: f_stream_add_to_cart_60m
      data_type: hugeint
    - name: f_stream_checkout_started_60m
      data_type: hugeint
    - name: f_stream_order_placed_60m
      data_type: hugeint
    - name: f_stream_cart_to_purchase_ratio_60m
      data_type: double
    - name: created
      data_type: timestamp
  - name: feat_customer_unified
    config:
      contract:
        enforced: true
    constraints:
    - type: primary_key
      columns:
      - customer_id
      - event_timestamp
    columns:
    - name: customer_id
      data_type: varchar
      constraints:
      - type: not_null
      - type: foreign_key
        to: ref('dim_customer')
        to_columns:
        - customer_id
      tests:
      - not_null
    - name: event_timestamp
      data_type: timestamp
      constraints:
      - type: not_null
      tests:
      - not_null
    - name: f_customer_total_orders_90d
      data_type: bigint
    - name: f_customer_paid_revenue_90d
      data_type: double
    - name: f_customer_avg_order_value_90d
      data_type: double
    - name: f_customer_distinct_categories_90d
      data_type: bigint
    - name: f_stream_views_60m
      data_type: hugeint
    - name: f_stream_add_to_cart_60m
      data_type: hugeint
    - name: f_stream_checkout_started_60m
      data_type: hugeint
    - name: f_stream_order_placed_60m
      data_type: hugeint
    - name: f_stream_cart_to_purchase_ratio_60m
      data_type: double
    - name: created
      data_type: timestamp
