namespace: edai2
image:
  repository: registry.invalid/edai2/worker
  tag: ""
  pullPolicy: IfNotPresent
workload:
  name: worker
  command: []
serviceAccount:
  name: edai2-worker
autoscaling:
  enabled: false
  minReplicaCount: 1
  maxReplicaCount: 1
  pollingInterval: null
  cooldownPeriod: null
  triggers: []
readinessProbe: {}
livenessProbe: {}
resources: {}
deploymentStrategy: {}
networkPolicy:
  enabled: true
