apiVersion: v1
kind: Pod
metadata:
  labels:
    edai2-buildkit-slot: "1"
spec:
  restartPolicy: Never
  serviceAccountName: jenkins-buildkit
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
    runAsGroup: 1000
    seccompProfile:
      type: RuntimeDefault
  containers:
    - name: buildkit
      image: moby/buildkit:v0.20.2-rootless@sha256:cb5bb371545222c430528556acfdf424144b69897f5deaad391bd227187e90df
      args: ["--oci-worker-no-process-sandbox"]
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop: ["ALL"]
      volumeMounts:
        - name: workspace
          mountPath: /workspace
  volumes:
    - name: workspace
      emptyDir: {}
